name: smart_arg
description: A smart command line argument parser for Dart that provides
  argument validation, static type checking, command execution, beautiful
  help generation and more.
version: 1.2.0
homepage: https://github.com/axrs/smart_arg

environment:
  sdk: ">=2.5.0 <3.0.0"

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.0
  build_runner: ^1.12.0
  build_test: ^2.0.0

dependencies:
  path: ^1.8.0
  reflectable: ^3.0.0
