name: smart_arg
description: A smart command line argument parser for Dart that provides
  argument validation, static type checking, command execution, beautiful
  help generation and more.
version: 2.0.0
homepage: https://github.com/jcowgar/smart_arg

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  lints: ^1.0.1
  test: ^1.18.2
  build_runner: ^2.1.4
  build_test: ^2.1.4

dependencies:
  path: ^1.8.0
  reflectable: ^3.0.4
